package com.lomen.mybatisdemo.user.dao;

import com.lomen.mybatisdemo.user.model.CityEntity;

public interface CityEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Thu Feb 08 11:56:06 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Thu Feb 08 11:56:06 CST 2018
     */
    int insert(CityEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Thu Feb 08 11:56:06 CST 2018
     */
    int insertSelective(CityEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Thu Feb 08 11:56:06 CST 2018
     */
    CityEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Thu Feb 08 11:56:06 CST 2018
     */
    int updateByPrimaryKeySelective(CityEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Thu Feb 08 11:56:06 CST 2018
     */
    int updateByPrimaryKey(CityEntity record);
}