package com.lomen.mybatisdemo.user.dao;

import com.lomen.mybatisdemo.user.model.SysRole;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface SysRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    int insert(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    int insertSelective(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    SysRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    int updateByPrimaryKeySelective(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    int updateByPrimaryKey(SysRole record);

    @ResultMap("BaseResultMap")
    @Select("select *  from t_sys_role")
    List<SysRole> selectAll();
    List<SysRole> selectAll(RowBounds rowBounds);
}