package com.lomen.mybatisdemo.user.dao;

import com.lomen.mybatisdemo.user.model.SysRes;

public interface SysResMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_res
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_res
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    int insert(SysRes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_res
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    int insertSelective(SysRes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_res
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    SysRes selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_res
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    int updateByPrimaryKeySelective(SysRes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_res
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    int updateByPrimaryKey(SysRes record);
}