package com.lomen.mybatisdemo.user.dao;

import com.lomen.mybatisdemo.user.model.SysRoleUserRel;

public interface SysRoleUserRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role_user_rel
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role_user_rel
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    int insert(SysRoleUserRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role_user_rel
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    int insertSelective(SysRoleUserRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role_user_rel
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    SysRoleUserRel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role_user_rel
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    int updateByPrimaryKeySelective(SysRoleUserRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role_user_rel
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    int updateByPrimaryKey(SysRoleUserRel record);
}