package com.lomen.mybatisdemo.user.dao;

import com.lomen.mybatisdemo.user.model.SysUser;

public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    int deleteByPrimaryKey(String identityid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    int insertSelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    SysUser selectByPrimaryKey(String identityid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    int updateByPrimaryKeySelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    int updateByPrimaryKey(SysUser record);
}