package com.lomen.mybatisdemo.user.model;

import java.io.Serializable;

public class SysRoleResRel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role_res_rel.ID
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role_res_rel.FK_ROLE_ID
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private String fkRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role_res_rel.FK_RES_ID
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private String fkResId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_role_res_rel
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_role_res_rel.ID
     *
     * @return the value of t_sys_role_res_rel.ID
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_role_res_rel.ID
     *
     * @param id the value for t_sys_role_res_rel.ID
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_role_res_rel.FK_ROLE_ID
     *
     * @return the value of t_sys_role_res_rel.FK_ROLE_ID
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public String getFkRoleId() {
        return fkRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_role_res_rel.FK_ROLE_ID
     *
     * @param fkRoleId the value for t_sys_role_res_rel.FK_ROLE_ID
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public void setFkRoleId(String fkRoleId) {
        this.fkRoleId = fkRoleId == null ? null : fkRoleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_role_res_rel.FK_RES_ID
     *
     * @return the value of t_sys_role_res_rel.FK_RES_ID
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public String getFkResId() {
        return fkResId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_role_res_rel.FK_RES_ID
     *
     * @param fkResId the value for t_sys_role_res_rel.FK_RES_ID
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public void setFkResId(String fkResId) {
        this.fkResId = fkResId == null ? null : fkResId.trim();
    }
}