package com.lomen.mybatisdemo.user.model;

import java.io.Serializable;
import java.util.Date;

public class SysRole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role.ID
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role.NAME
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role.REMARK
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role.CREATE_BY
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role.CREATE_TIME
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role.LAST_MODIFY_BY
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private String lastModifyBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role.LAST_MODIFY_TIME
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private Date lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_role
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_role.ID
     *
     * @return the value of t_sys_role.ID
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_role.ID
     *
     * @param id the value for t_sys_role.ID
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_role.NAME
     *
     * @return the value of t_sys_role.NAME
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_role.NAME
     *
     * @param name the value for t_sys_role.NAME
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_role.REMARK
     *
     * @return the value of t_sys_role.REMARK
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_role.REMARK
     *
     * @param remark the value for t_sys_role.REMARK
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_role.CREATE_BY
     *
     * @return the value of t_sys_role.CREATE_BY
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_role.CREATE_BY
     *
     * @param createBy the value for t_sys_role.CREATE_BY
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_role.CREATE_TIME
     *
     * @return the value of t_sys_role.CREATE_TIME
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_role.CREATE_TIME
     *
     * @param createTime the value for t_sys_role.CREATE_TIME
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_role.LAST_MODIFY_BY
     *
     * @return the value of t_sys_role.LAST_MODIFY_BY
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public String getLastModifyBy() {
        return lastModifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_role.LAST_MODIFY_BY
     *
     * @param lastModifyBy the value for t_sys_role.LAST_MODIFY_BY
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public void setLastModifyBy(String lastModifyBy) {
        this.lastModifyBy = lastModifyBy == null ? null : lastModifyBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_role.LAST_MODIFY_TIME
     *
     * @return the value of t_sys_role.LAST_MODIFY_TIME
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_role.LAST_MODIFY_TIME
     *
     * @param lastModifyTime the value for t_sys_role.LAST_MODIFY_TIME
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }
}