package com.lomen.mybatisdemo.user.model;

import java.io.Serializable;
import java.util.Date;

public class SysRes implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_res.ID
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_res.PARENT_ID
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_res.NAME
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_res.TYPE
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_res.PERMISSION
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_res.HREF
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private String href;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_res.TARGET
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private String target;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_res.ICON
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_res.LEVEL
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_res.SORT
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_res.CREATE_BY
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_res.CREATE_TIME
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_res.LAST_MODIFY_BY
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private String lastModifyBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_res.LAST_MODIFY_TIME
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private String lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_res
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_res.ID
     *
     * @return the value of t_sys_res.ID
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_res.ID
     *
     * @param id the value for t_sys_res.ID
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_res.PARENT_ID
     *
     * @return the value of t_sys_res.PARENT_ID
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_res.PARENT_ID
     *
     * @param parentId the value for t_sys_res.PARENT_ID
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_res.NAME
     *
     * @return the value of t_sys_res.NAME
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_res.NAME
     *
     * @param name the value for t_sys_res.NAME
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_res.TYPE
     *
     * @return the value of t_sys_res.TYPE
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_res.TYPE
     *
     * @param type the value for t_sys_res.TYPE
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_res.PERMISSION
     *
     * @return the value of t_sys_res.PERMISSION
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_res.PERMISSION
     *
     * @param permission the value for t_sys_res.PERMISSION
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_res.HREF
     *
     * @return the value of t_sys_res.HREF
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public String getHref() {
        return href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_res.HREF
     *
     * @param href the value for t_sys_res.HREF
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public void setHref(String href) {
        this.href = href == null ? null : href.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_res.TARGET
     *
     * @return the value of t_sys_res.TARGET
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_res.TARGET
     *
     * @param target the value for t_sys_res.TARGET
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public void setTarget(String target) {
        this.target = target == null ? null : target.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_res.ICON
     *
     * @return the value of t_sys_res.ICON
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_res.ICON
     *
     * @param icon the value for t_sys_res.ICON
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_res.LEVEL
     *
     * @return the value of t_sys_res.LEVEL
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_res.LEVEL
     *
     * @param level the value for t_sys_res.LEVEL
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_res.SORT
     *
     * @return the value of t_sys_res.SORT
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_res.SORT
     *
     * @param sort the value for t_sys_res.SORT
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_res.CREATE_BY
     *
     * @return the value of t_sys_res.CREATE_BY
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_res.CREATE_BY
     *
     * @param createBy the value for t_sys_res.CREATE_BY
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_res.CREATE_TIME
     *
     * @return the value of t_sys_res.CREATE_TIME
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_res.CREATE_TIME
     *
     * @param createTime the value for t_sys_res.CREATE_TIME
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_res.LAST_MODIFY_BY
     *
     * @return the value of t_sys_res.LAST_MODIFY_BY
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public String getLastModifyBy() {
        return lastModifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_res.LAST_MODIFY_BY
     *
     * @param lastModifyBy the value for t_sys_res.LAST_MODIFY_BY
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public void setLastModifyBy(String lastModifyBy) {
        this.lastModifyBy = lastModifyBy == null ? null : lastModifyBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_res.LAST_MODIFY_TIME
     *
     * @return the value of t_sys_res.LAST_MODIFY_TIME
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public String getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_res.LAST_MODIFY_TIME
     *
     * @param lastModifyTime the value for t_sys_res.LAST_MODIFY_TIME
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public void setLastModifyTime(String lastModifyTime) {
        this.lastModifyTime = lastModifyTime == null ? null : lastModifyTime.trim();
    }
}