package com.lomen.mybatisdemo.user.model;

import java.io.Serializable;

public class SysUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.IdentityID
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private String identityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.UserID
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.Password
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.FullName
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private String fullname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.EmployCode
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private String employcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.Email
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.MobileNo
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private String mobileno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.FK_OrganizationID
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private String fkOrganizationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.Status
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.LoginID
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private String loginid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_user
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.IdentityID
     *
     * @return the value of t_sys_user.IdentityID
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public String getIdentityid() {
        return identityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.IdentityID
     *
     * @param identityid the value for t_sys_user.IdentityID
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public void setIdentityid(String identityid) {
        this.identityid = identityid == null ? null : identityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.UserID
     *
     * @return the value of t_sys_user.UserID
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.UserID
     *
     * @param userid the value for t_sys_user.UserID
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.Password
     *
     * @return the value of t_sys_user.Password
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.Password
     *
     * @param password the value for t_sys_user.Password
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.FullName
     *
     * @return the value of t_sys_user.FullName
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.FullName
     *
     * @param fullname the value for t_sys_user.FullName
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public void setFullname(String fullname) {
        this.fullname = fullname == null ? null : fullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.EmployCode
     *
     * @return the value of t_sys_user.EmployCode
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public String getEmploycode() {
        return employcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.EmployCode
     *
     * @param employcode the value for t_sys_user.EmployCode
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public void setEmploycode(String employcode) {
        this.employcode = employcode == null ? null : employcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.Email
     *
     * @return the value of t_sys_user.Email
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.Email
     *
     * @param email the value for t_sys_user.Email
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.MobileNo
     *
     * @return the value of t_sys_user.MobileNo
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public String getMobileno() {
        return mobileno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.MobileNo
     *
     * @param mobileno the value for t_sys_user.MobileNo
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public void setMobileno(String mobileno) {
        this.mobileno = mobileno == null ? null : mobileno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.FK_OrganizationID
     *
     * @return the value of t_sys_user.FK_OrganizationID
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public String getFkOrganizationid() {
        return fkOrganizationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.FK_OrganizationID
     *
     * @param fkOrganizationid the value for t_sys_user.FK_OrganizationID
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public void setFkOrganizationid(String fkOrganizationid) {
        this.fkOrganizationid = fkOrganizationid == null ? null : fkOrganizationid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.Status
     *
     * @return the value of t_sys_user.Status
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.Status
     *
     * @param status the value for t_sys_user.Status
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.LoginID
     *
     * @return the value of t_sys_user.LoginID
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public String getLoginid() {
        return loginid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.LoginID
     *
     * @param loginid the value for t_sys_user.LoginID
     *
     * @mbggenerated Thu Feb 08 15:38:13 CST 2018
     */
    public void setLoginid(String loginid) {
        this.loginid = loginid == null ? null : loginid.trim();
    }
}